package com.coltcn.ims.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER_DT".
 */
public class OrderDt {

    private Long id;
    private Long blid;
    private String stockName;
    private Integer quantity;
    private java.util.Date price;

    public OrderDt() {
    }

    public OrderDt(Long id) {
        this.id = id;
    }

    public OrderDt(Long id, Long blid, String stockName, Integer quantity, java.util.Date price) {
        this.id = id;
        this.blid = blid;
        this.stockName = stockName;
        this.quantity = quantity;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBlid() {
        return blid;
    }

    public void setBlid(Long blid) {
        this.blid = blid;
    }

    public String getStockName() {
        return stockName;
    }

    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public java.util.Date getPrice() {
        return price;
    }

    public void setPrice(java.util.Date price) {
        this.price = price;
    }

}
